exclude: examples/.*/settings/derex/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        exclude: docs/conf.py|examples
        args:
          - --ignore-missing-imports

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: docs/html_templates/layout.html
