schedules:
  - cron: "20 05 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-pipelines/minimal.yml
    parameters:
      JOB_VARIANT: UnPinned
      PIN_VERSIONS:

  - template: azure-pipelines/minimal.yml
    parameters:
      JOB_VARIANT: Pinned
      PIN_VERSIONS: yes
