schedules:
  - cron: "20 05 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-pipelines/test.yml
    parameters:
      OPENEDX_RELEASE: ironwood
      OPENEDX_RELEASE_CAPITALIZED: Ironwood
  - template: azure-pipelines/test.yml
    parameters:
      OPENEDX_RELEASE: juniper
      OPENEDX_RELEASE_CAPITALIZED: Juniper
