schedules:
  - cron: "20 05 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

stages:
  - template: azure_pipelines/build/main.yml
  - template: azure_pipelines/test/main.yml
  - template: azure_pipelines/push/main.yml

variables:
  - name: UBUNTU_VERSION
    value: ubuntu-latest
  - name: needs_build
    value: "false"
