# DO NOT EDIT THIS FILE!
# IT CAN BE OVERWRITTEN ON UPGRADE.
# Generated by derex.runner 0.0.3.dev1

import os


DATABASES = {
    "default": {
        "ATOMIC_REQUESTS": True,
        "ENGINE": "django.db.backends.mysql",
        "HOST": "mysql",
        "NAME": os.environ["MYSQL_DB_NAME"],
        "PASSWORD": "secret",
        "PORT": "3306",
        "USER": "root",
    }
}
