parameters:
  - name: JOB_VARIANT
    type: string
  - name: AS_PYTHON_PACKAGE
    type: boolean
    default: False

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
    displayName: "Use Python 3.7"

  - script: |
      pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip -U pip setuptools
      { [ "${{ parameters.JOB_VARIANT }}" == "Pinned" ] && pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip -r requirements_dev.txt || true; }
      { [ "${{ parameters.JOB_VARIANT }}" != "Pinned" ] && pip3 install --cache-dir $(Pipeline.Workspace)/.cache/pip . https://github.com/Abstract-Tech/derex.runner/tarball/master#egg=derex.runner || true; }
    displayName: "Install derex.runner and dev requirements"

  - script: |
      { [ "${{ parameters.AS_PYTHON_PACKAGE }}" == True ] && pip3 install . || true; }
      { [ "${{ parameters.AS_PYTHON_PACKAGE }}" != True ] && pip3 install -e . || true; }
    displayName: "Install derex.forum"
