stages:
  - stage: Test
    jobs:
      - template: test_version.yml
        parameters:
          OPENEDX_RELEASE: ironwood
          OPENEDX_RELEASE_CAPITALIZED: Ironwood
      - template: test_version.yml
        parameters:
          OPENEDX_RELEASE: juniper
          OPENEDX_RELEASE_CAPITALIZED: Juniper
      - template: test_version.yml
        parameters:
          OPENEDX_RELEASE: koa
          OPENEDX_RELEASE_CAPITALIZED: Koa
